create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 160),
  status text not null default 'active' check (status in ('active','paused','archived')),
  core_version text not null default '1.1',
  software_product_version text not null default '1.1',
  runtime_version text not null default '1.0',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create index projects_owner_user_id_idx on public.projects(owner_user_id);

create table public.project_profiles (
  project_id uuid primary key references public.projects(id) on delete cascade,
  revision bigint not null default 0 check (revision >= 0),
  core_state jsonb not null default '{}'::jsonb,
  specialization_state jsonb not null default '{}'::jsonb,
  current_nba_action_id uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  source_revision_parent bigint
);

create table public.project_profile_revisions (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  revision bigint not null check (revision >= 0),
  core_state jsonb not null,
  specialization_state jsonb not null,
  change_summary text,
  action_id uuid,
  created_at timestamptz not null default now(),
  unique(project_id, revision)
);

create index project_profile_revisions_project_idx
  on public.project_profile_revisions(project_id, revision desc);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_profiles enable row level security;
alter table public.project_profile_revisions enable row level security;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.projects to authenticated;
grant select on public.project_profiles to authenticated;
grant select on public.project_profile_revisions to authenticated;

create policy "profiles_select_own" on public.profiles for select to authenticated
using ((select auth.uid()) = id);

create policy "profiles_insert_own" on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

create policy "profiles_update_own" on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "projects_select_own" on public.projects for select to authenticated
using ((select auth.uid()) = owner_user_id);

create policy "projects_insert_own" on public.projects for insert to authenticated
with check ((select auth.uid()) = owner_user_id);

create policy "projects_update_own" on public.projects for update to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);

create policy "projects_delete_own" on public.projects for delete to authenticated
using ((select auth.uid()) = owner_user_id);

create policy "project_profiles_select_own" on public.project_profiles for select to authenticated
using (exists (
  select 1 from public.projects p
  where p.id = project_profiles.project_id
    and p.owner_user_id = (select auth.uid())
));

create policy "project_profile_revisions_select_own"
on public.project_profile_revisions for select to authenticated
using (exists (
  select 1 from public.projects p
  where p.id = project_profile_revisions.project_id
    and p.owner_user_id = (select auth.uid())
));

revoke insert, update, delete on public.project_profiles from authenticated;
revoke insert, update, delete on public.project_profile_revisions from authenticated;
