name: Database Tests

on:
  pull_request:
    paths:
      - "supabase/**"
      - ".github/workflows/database.yml"
  push:
    branches: [main]
    paths:
      - "supabase/**"
      - ".github/workflows/database.yml"

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase start
      - run: supabase test db
